services:
  users-db:
    image: postgres:16
    container_name: users-db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management # Using the image with the management plugin
    container_name: rabbitmq
    hostname: rabbitmq # Set hostname for internal communication
    ports:
      - "5672:5672" # Standard AMQP port
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest # Default username (change for production)
      RABBITMQ_DEFAULT_PASS: guest # Default password (change for production)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent data storage
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s




volumes:
  users_db_data:
  rabbitmq_data:
    driver: local
